#!/usr/bin/env bash
# Regenerate the Obsidian DevTools inject script from theme.css.
#
# Why this exists:
#   Mac App Store Obsidian runs in a sandbox. macOS Sequoia 15+ tags any
#   file created by `cp` from Terminal with `com.apple.provenance`, and the
#   sandbox refuses to load those files as theme resources. So we cannot
#   ship kami as a themes/ folder via filesystem copy.
#
#   The workaround is to inject the CSS as a snippet via Obsidian's own
#   Vault API from the DevTools console — files written by Obsidian itself
#   have Obsidian provenance and load fine. This script encodes theme.css
#   to base64 and wraps it in a ready-to-paste console script.
#
# Workflow:
#   1. Edit theme.css (and/or manifest.json — though manifest is unused in
#      snippet mode, kept for future Phase 2 theme-gallery submission).
#   2. Run:  ./sync.sh
#   3. Open the generated inject-kami-snippet.js, copy all, paste into
#      Obsidian DevTools Console (Cmd+Option+I), press Enter.
#   4. Toggle the kami snippet off and on in
#      Settings → Appearance → CSS Snippets to force reload.

set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CSS_PATH="$SRC_DIR/theme.css"
OUT_PATH="$SRC_DIR/inject-kami-snippet.js"

if [[ ! -f "$CSS_PATH" ]]; then
    echo "✗ theme.css not found at $CSS_PATH" >&2
    exit 1
fi

# Git stores text with LF, but Windows worktrees may materialize CRLF. Normalize
# before measuring and encoding so the generated injector is byte-for-byte
# reproducible on Windows, macOS, and Linux.
NORMALIZED_CSS=$(mktemp)
trap 'rm -f "$NORMALIZED_CSS"' EXIT
sed 's/\r$//' "$CSS_PATH" > "$NORMALIZED_CSS"

CSS_LINES=$(wc -l < "$NORMALIZED_CSS" | tr -d ' ')
CSS_BYTES=$(wc -c < "$NORMALIZED_CSS" | tr -d ' ')
B64=$(base64 -i "$NORMALIZED_CSS" | tr -d '\n')

cat > "$OUT_PATH" << JSEOF
// === Kami Reader CSS Snippet Injector ===
// Auto-generated by sync.sh from theme.css (${CSS_LINES} lines, ${CSS_BYTES} bytes)
//
// Usage:
//   1. Copy this entire file's contents.
//   2. In Obsidian: Cmd+Option+I → Console tab → paste → Enter.
//   3. Set Settings → Appearance → Themes to Default. This snippet contains
//      the complete Kami Reader theme and must not be combined with another theme.
//   4. If you don't see changes: Settings → Appearance → CSS Snippets
//      → toggle kami off then on (forces reload of modified snippet).
//
// Why this is needed (the short version):
//   macOS Sequoia 15 tags cp'd files with com.apple.provenance; App Store
//   Obsidian sandbox refuses to load them as theme resources. Files written
//   through app.vault from inside Obsidian carry Obsidian provenance and
//   load fine. So we inject via the Vault API instead of copying files.

const b64 = "${B64}";

const bytes = Uint8Array.from(atob(b64), c => c.charCodeAt(0));
const css = new TextDecoder('utf-8').decode(bytes);

async function warnIfThemeIsActive() {
  try {
    const appearance = JSON.parse(
      await app.vault.adapter.read('.obsidian/appearance.json')
    );
    const activeTheme = appearance.cssTheme;
    if (typeof activeTheme === 'string' && activeTheme.trim()) {
      console.warn(
        '⚠ "' + activeTheme + '" is active. The kami snippet contains the full '
        + 'Kami Reader theme. Set Settings → Appearance → Themes to Default, '
        + 'then enable only the kami snippet.'
      );
    }
  } catch (e) {
    console.warn('⚠ Kami was injected, but could not check the active theme:', e);
  }
}

try {
  const existing = app.vault.getAbstractFileByPath('.obsidian/snippets/kami.css');
  if (existing) {
    await app.vault.modify(existing, css);
    console.log('✓ kami.css updated (' + css.length + ' chars)');
  } else {
    await app.vault.create('.obsidian/snippets/kami.css', css);
    console.log('✓ kami.css created (' + css.length + ' chars)');
    console.log('  → enable it in Settings → Appearance → CSS Snippets');
  }
  await warnIfThemeIsActive();
} catch (e) {
  console.error('Injection failed:', e);
  throw e;
}
JSEOF

echo "✓ Generated $OUT_PATH"
echo "  Source: theme.css ($CSS_LINES lines, $CSS_BYTES bytes)"
echo "  Output: $(wc -c < "$OUT_PATH" | tr -d ' ') bytes"
echo ""
echo "Next: open the file, copy all, paste into Obsidian DevTools Console."
echo "      Before enabling the full snippet, set Appearance → Themes to Default."
